<?php require_once(realpath(dirname(__FILE__)."/displayFunctions.php")); ?>

			</div>
		</div>
	</div>
	
<div class="contenu" id="content">

	<div id="fb-root"></div>
	


	<div class="row itemtitle">
		<p class='p0 pdetail'> <h1 style="margin:0px!important;font-size:25px;"> <i class="fa fa-calendar-o calendaricon"></i> <?php echo dateToFrench($this->event->getdate()); ?> - <?php echo $this->escape($this->event->getSpot()->getName());?></h1>
			
		</p>
	</div>
	
	
	
<div class="row itemtest tete" style="padding-bottom:5%;padding-left:0px;padding-top:0px;" id="<?php echo $this->date ?>"style="padding:0px;" >


<!-- IMAGE -->
		<div style="margin: auto;width: 100%;height: 300px;overflow: hidden;margin-bottom: 3%;">
			<a class='linkblue' onclick="trackOutboundLink('<?php echo addslashes($this->escape($this->event->getName())); ?>');" rel="nofollow" target=\"_blank\" href="<?php echo $this->escape($this->event->getLinkFb()); ?>" title='Lien Facebook'><img src="<?php echo $this->escape($this->event->getImg());?>" style="width:100%;" ></a>
		</div>
<div style="padding-left:5%;">
	<div class="col-md-2"><div class="vote votedetail">
		<div id="participe<? $idFb = explode("/",$this->escape($this->event->getLinkFb()))[4]; echo $idFb; ?>" >
			<div class="aligncenter voteinfos" style ="width: 100%;opacity: .5;font-size: 22px;margin-left:0px;">
				<a class="lienvote likebutton like<?php echo $this->escape($this->event->getId()); ?>" name="<?php echo $this->escape($this->event->getId()); ?>" onclick="rsvp(<?php echo $idFb; ?>)">Participer</i>
				</a>
			</div>
		</div>
		
		<?php if($this->escape($this->event->getAttending()) == 0): ?>
			<div class="aligncenter <?php echo $this->escape($this->event->getId()); ?>">-</div>
		<?php else: ?>
			<div class="aligncenter <?php echo $this->escape($this->event->getId()); ?>">
			<p class='p0 pdetail nombreAttending'><?php echo $this->escape($this->event->getAttending()); ?></p></div>
		<?php endif; ?>
		
		<div class="aligncenter">Participants</div></p>		
	</div>
</div>

<div class="col-md-10" style="padding-left:5%;"> 



	<!-- SPOT -->
	<p class='p0 pdetail'>
		<i class='fa fa-map-marker'></i>
			<span class="spot" ><strong><?php echo $this->escape($this->event->getSpot()->getName());?></strong> </span> - <?PHP echo $this->escape($this->event->getSpot()->getAddress()).', '.$this->escape($this->event->getSpot()->getCity());?>
		</p>
	
	<!-- LIEN FACEBOOK -->
	<p class='p0 pdetail' > <a class='linkblue' onclick="trackOutboundLink('<?php echo addslashes($this->escape($this->event->getName())); ?>');" rel="nofollow" target=\"_blank\" href="<?php echo $this->escape($this->event->getLinkFb()); ?>" title='Lien Facebook'><i class='fa fa-facebook-square'></i> <?php echo $this->escape($this->event->getName()); ?></a></p>
	
	<script type="text/javascript">
		trackViewEvent('<?php echo addslashes($this->escape($this->event->getName())); ?>');
	</script>
	
	<!-- ARTISTES -->
	<p class='p0 pdetail maxWidht85'  ><i class='fa fa-music'></i>
		<?php 
			$array = array();
			foreach ($this->event->getArtists() as $artist){
				$element = "";
				$element = $artist->getName();
				if(trim($artist->getLabel()) != ""){
					$element = $element.' ('.trim($artist->getLabel());
					if(trim($artist->getCountry()) != ""){
						$element = $element. ' - ' . trim($artist->getCountry()).')';
					} else {
						$element = $element.')';
					}
				} elseif (trim($artist->getCountry()) != ""){
					$element = $element. ' ('.trim($artist->getCountry()).')';
				}
				$array[] = $element;
			}
			echo implode(', ', $array);
		?>
	</p>
	
	<!-- TIMES -->
	<?php
		$heure_debut = explode(":", $this->escape($this->event->getHeureDebut()));
		$heure_fin = explode(":", $this->escape($this->event->getHeureFin()));
		if(!($heure_debut[0] == 'NULL' || $heure_debut[0] == '')):
			if($heure_fin[0] == 'NULL' || $heure_fin[0] == ''):
				if($heure_debut[0] >= '08' && $heure_fin[0] <= '19' && $heure_debut[0] <= '19' && $heure_fin[0] >= '08'): ?>
					<p class='p0 pdetail'>
						<i class='fa fa-sun-o'></i> Day - 
						<i class='fa fa-clock-o'></i>
						<?php echo $this->escape($this->event->getHeureDebut()); ?>
					</p>
				<?php elseif($heure_debut[0] >= '08' && $heure_fin[0] >= '19'): ?>
					<p class='p0 pdetail'>
						<i class='fa fa-sun-o'></i> Day & <i class='fa fa-moon-o'></i> Night
- 						<i class='fa fa-clock-o'></i>
						<?php echo $this->escape($this->event->getHeureDebut()); ?>
					</p>
				<?php else: ?>
					<p class='p0 pdetail'>
					<i class='fa fa-moon-o'></i> Night - 
					<i class='fa fa-clock-o'></i>
							<?php echo $this->escape($this->event->getHeureDebut()); ?>
					</p>
				<?php endif; ?>
			<?php else: ?>
				<?php if($heure_debut[0] >= '08' && $heure_fin[0] <= '19' && $heure_debut[0] <= '19' && $heure_fin[0] >= '08'): ?>
					<p class='p0 pdetail'>
						<i class='fa fa-sun-o'></i> Day - 
						<i class='fa fa-clock-o'></i>
						<?php echo $this->escape($this->event->getHeureDebut())."/".$this->escape($this->event->getHeureFin()); ?>	
					</p>
				<?php elseif($heure_debut[0] >= '08' && $heure_fin[0] >= '19'): ?>
					<p class='p0 pdetail'>
						<i class='fa fa-sun-o'></i> Day & <i class='fa fa-moon-o'></i> Night - 
						<i class='fa fa-clock-o'></i>
						<?php echo $this->escape($this->event->getHeureDebut())."/".$this->escape($this->event->getHeureFin()); ?>	
					</p>
				<?php else: ?>
					<p class='p0 pdetail'>
					<i class='fa fa-moon-o'></i> Night - 
					<i class='fa fa-clock-o'></i>
					<?php echo $this->escape($this->event->getHeureDebut())."/".$this->escape($this->event->getHeureFin()); ?>
					</p>
				<?php endif; ?>
			<?php endif; ?>
	<?php endif; ?>
		
	<!-- PRICES -->
	<p class='p0 pdetail paddingTop5'>
		<?php 
		$i = 0;
		foreach($this->event->getPrices() as $price): 
		?>
		<span class='label label-primary pricelabel pricelabeldetail'>
			<?php if($price->getLink() != "" || $price->getLink() != NULL): ?>
				<a class="linkwhite uBold" onclick="trackOutboundLink('<?php echo addslashes($this->escape($this->event->getName())); ?> / Ticket');" rel="nofollow" href="<?php echo $price->getLink() ?>" target="_blank"><?php echo $price->getType()->getName(); ?></a>
			<?php else: ?>
				<span class="uBold"> <?php echo $price->getType()->getName(); ?></span>
			<?php endif; ?>
			-
			<?php echo $price->getPrice(); ?> € 
		</span></h5>
		<?php endforeach; ?>
	</p>
	
	</div>
	<!-- GENRES -->
	<p class='p0 pdetail'>
		<?php foreach ($this->event->getGenres() as $genre): ?>
			<span class="label label-default"><strong><?php echo $this->escape($genre); ?></strong></span>
		<?php endforeach; ?>
	</p>

	<!-- JEUX CONCOURS -->
	<?php 
		$idPostConcours = $this->event->getConcours()->getIdPostConcours();
		if(!(is_null($idPostConcours) || trim($idPostConcours) == '' || trim($idPostConcours) == 0)): 
	?>
		<div class='jeuxConcours'>
			<a  onclick="trackOutboundLink('<?php echo addslashes($this->escape($this->event->getName())); ?> / Concours');" href="https://www.facebook.com/<?php echo Zend_Registry::get('Fb_Link') ?>/photos/<?php echo $idPostConcours ?>" target="blank"><i class='fa fa-trophy displayNoneOnMobile'></i> Jeu Concours</a>
		</div>
	<?php endif; ?>
	
	</div>
	
	</div>

	<div class=" row itemtest tete" style="padding-top:20px;padding-bottom:20px;margin-bottom:20px;font-size:15px;">
	<?php if(count($this->pastEventsFromClub) > 0): ?>
		<h2 style="padding-left:5%;" >Events passés les plus populaires à <?php echo $this->event->getSpot()->getName(); ?> </h2>
		<ul style="padding-left:10%;">
			<?php foreach($this->pastEventsFromClub as $pastEvent): ?>
				<li><?php echo $pastEvent->getName() ?> - <?php echo $pastEvent->getAttending() ?> <i class="fa fa-male"></i></li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
	
	<?php if(count($this->pastEventsFromClub) > 0): ?>
		<h2 style="padding-left:5%;">Events à venir les plus populaires à <?php echo $this->event->getSpot()->getName(); ?> </h2>
		<ul style="padding-left:10%;">
			<?php foreach($this->upcomingEventsFromClub as $pastEvent): ?>
				<li><?php echo $pastEvent->getName() ?> - <?php echo $pastEvent->getAttending() ?> <i class="fa fa-male"></i></li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
	</div>
	
<div style="text-align:center; margin-bottom: 20px;" id="marginBot">
	<?php echo $this->partial("facebookFrame.phtml") ?>
</div>

