<div class="fb-page" id="marginBotFB" data-href="https://www.facebook.com/<?php echo Zend_Registry::get('Fb_Link') ?>/?fref=ts" data-width="450" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="true" data-show-posts="false">
	<div class="fb-xfbml-parse-ignore">
		<blockquote cite="https://www.facebook.com/<?php echo Zend_Registry::get('Fb_Link') ?>/?fref=ts"><a href="https://www.facebook.com/<?php echo Zend_Registry::get('Fb_Link') ?>/?fref=ts"><?php echo Zend_Registry::get('Fb_Name') ?></a>
		</blockquote>
	</div>
</div>