		</div>
	</div>
</div>

<div class="contenu" id="content" style="margin-bottom: 40px;">	
	<div class="cookie">
		<div class="infoCookie">
			<div class="titreInfoCookie">
				INFORMATIONS SUR LES COOKIES DU SITE WWW.HAPTALYON.FR
			</div>
			Lors de la consultation de notre site www.haptalyon.fr, des cookies sont déposés sur votre ordinateur, votre mobile ou votre tablette.<br/>
			Notre site est conçu pour être particulièrement attentif aux besoins et attentes de nos utilisateurs. C’est entre autres pour cela que nous faisons usage de cookies afin par exemple de vous identifier.<br/>
			Cette page vous permet de mieux comprendre comment fonctionnent les cookies et comment utiliser les outils afin de les paramétrer.
		</div>

		<br>

		<div class="infoCookie">
			<a href="#qu_est_ce_qu_un_cookie">
				<u>> QU’EST-CE QU’UN COOKIE ET COMMENT EST-IL UTILISÉ ?</u>
			</a><br>
			<a href="#quels_sont_les_cookies_utilises">
				<u>> QUELS SONT LES COOKIES UTILISÉS SUR WWW.HAPTALYON.FR ?</u>
			</a><br>
			<a href="#comment_accepter_ou_refuser_les_cookies">
				<u>> COMMENT ACCEPTER OU REFUSER LES COOKIES ?</u>
			</a><br>
		</div>

		<br>

		<div class="infoCookie anchor" id="qu_est_ce_qu_un_cookie">
			<div class="titreInfoCookie">
				QU’EST-CE QU’UN COOKIE ET COMMENT EST-IL UTILISÉ ?
			</div>
			Un cookie est un petit fichier déposé sur votre navigateur internet, lorsque vous accédez à certains sites web. Les cookies permettent à un site web de reconnaître les préférences d’un utilisateur telles que ce dernier les a définies lors d’une précédente visite sur ce même site. Un cookie en lui-même ne contient, ni ne recueille, d’informations. En revanche lorsqu’il est « lu » par un serveur en liaison avec un navigateur web, il peut aider un site web à offrir un service plus convivial.
		</div>

		<br>

		<div class="infoCookie anchor" id="quels_sont_les_cookies_utilises">
			<div class="titreInfoCookie">
				QUELS SONT LES COOKIES UTILISÉS SUR WWW.HAPTALYON.FR ?
			</div>
			<strong>Les cookies www.haptalyon.fr :</strong><br/>
			Il s’agit des cookies déposés par www.haptalyon.fr sur votre terminal pour les besoins de la navigation sur notre site internet, l’optimisation et la personnalisation de nos services sur le site.<br>
			<strong>Les cookies tiers :</strong><br/>
			Il s’agit des cookies déposés par des sociétés tierces (par des partenaires, par exemple Google).<br>
			Dans le cadre des partenariats publicitaires nous pouvons être amenés à transmettre aux partenaires qui agissent pour notre compte des données concernant la navigation sur notre site. Nous veillons à ce que les sociétés partenaires acceptent de traiter les informations collectées sur le site www.haptalyon.fr exclusivement pour nos besoins et conformément à nos instructions, dans le respect de la loi «Informatique et Libertés « du 6 janvier 1978 modifiée et s’engagent à mettre en œuvre des mesures appropriées de sécurisation et de protection de la confidentialité des données.<br>
			<strong>Les cookies analytiques :</strong><br/> 
			Il s’agit des cookies qui nous permettent de connaître l’utilisation et les performances de notre site et d’en améliorer le fonctionnement (par exemple, les pages le plus souvent consultées, recherches des internautes dans le moteur…).
		</div>

		<br>

		<div class="infoCookie anchor" id="comment_accepter_ou_refuser_les_cookies">
			<div class="titreInfoCookie">
				COMMENT ACCEPTER OU REFUSER LES COOKIES ?
			</div>
			<strong>Le paramétrage de votre navigateur internet :</strong><br/>
			Les menus d’options internet de votre navigateur doivent vous permettre de désactiver facilement les cookies. Lorsque vous visitez le site www.haptalyon.fr, les services de ses partenaires (tels que notamment les agences de publicité, organismes de certification de la diffusion) peuvent aussi créer des cookies sur votre ordinateur. Il faut préciser qu’une entité qui dépose un cookie sur votre ordinateur n’aura d’accès qu’à son seul cookie.<br>
			<strong>Les conseils de la CNIL pour bloquer les cookies :</strong><br/>
			<a href="http://www.cnil.fr/vos-droits/vos-traces/les-cookies/conseils-aux-internautes/" target="_blank">http://www.cnil.fr/vos-droits/vos-traces/les-cookies/conseils-aux-internautes/</a><br>
			<strong>Le paramétrage sur une plateforme de gestion des cookies :</strong><br>
			Vous pouvez gérer vos cookies en vous rendant sur des plateformes de gestion des cookies proposées par les professionnels de la publicité. <br>
			<strong>D’autres informations sur les cookies :</strong><br>
			Sur le site de la CNIL : <a href="http://www.cnil.fr/vos-droits/vos-traces/les-cookies/" target="_blank">http://www.cnil.fr/vos-droits/vos-traces/les-cookies/</a>
		</div>

		<br>
	</div>
</div>