			<p class="slogan">Nos partenaires</p>
		</div>
</div>


<div class="contenu responsive" id="content">



<?php 
$int = 0 ;

foreach($this->partners as $partner): 


if ($int%3 == 0) { ?>

	    <div class="col-xs-12">
		<div class="row">
	<?PHP } ?>	
	
		<div class="responsMobilePartner">
			
			 
			  <a class=" tilea" target="_blank "href="<?php echo $partner['link'] ?>">
			   <div class=" tile text-center">
				<h3 ><?php echo $partner['name'] ?></h3>
				</div>
				</a>
				
			
		</div>
		
	
	
<?php 
$int=$int+1;

 if ($int%3 == 0) { ?>

	    </div>
		</div>
<?PHP
 } 
endforeach; ?>



</div>

